version: 2
jobs:
  build:
      docker:
        - image: circleci/android:api-26-alpha
      working_directory: ~/code
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - run:
            name: Assemble build
            command: ./gradlew :app:assembleFreeAppSpectorDebug
        - run:
            name: Upload to HockeyApp
            command: sh ./.circleci/hockeyapp-upload.sh
            environment:
                APK_PATH: app/build/outputs/apk/freeAppSpector/debug/app-free-appSpector-debug.apk
